name: Greetings

on: 
  pull_request_target:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  greeting:
    environment: check
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.check }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Make commit
      run: |
        touch hello.txt
        git add hello.txt
        git commit
        git push
